permlink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Essential Elements"
  description: |
    All natural, pure and organic essential oil for overall wellness.
  font_url: "https://fonts.googleapis.com/css?family=Catamaran:400,700&display=swap"
