title: "Buttons"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to overuse buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description: |
      Default to using the basic button. It should always be used in front of light backgrounds.
    width: "12em"
    shop-btn:
      title: "Shop"
      description: |
        Default to using the basic button. It should always be used in front of light backgrounds.
      width: "12em"
  ghost:
    title: "Ghost"
    description: |
      The ghost button is specifically for banner, where it will be placed in fron tof busy images.
    background: "--color-light-blue"
