patterns:
  banners:
    fields:
      - name: heading
        type: string
        example: "Products you can count on!"
      - name: text
        type: string
        example: "All our products are certified organic, plant based and not tested on animals."
  home-banner:
    fields:
      - name: heading
        type: string
        example: "Enhance your wellbeing!"
      - name: text
        type: string
        example: "Improve your life with Essential Elements pure oils!"
